
import { University, ComparisonMetric } from './types';

export const UNIVERSITIES: University[] = [
  {
    id: 'nu',
    name: 'Nazarbayev University',
    shortName: 'NU',
    city: 'Астана',
    rating: 98,
    image: 'https://images.unsplash.com/photo-1551135049-8a33b5883817?q=80&w=800&auto=format&fit=crop',
    description: 'Автономная организация образования, исследовательский университет международного уровня. Обучение полностью на английском языке. 270+ учебных и исследовательских лабораторий. До 98% студентов финансируются государством.',
    type: 'Autonomous',
    founded: 2010,
    students: 7000,
    employmentRate: 96,
    dormitory: true,
    militaryDept: false,
    coordinates: { lat: 51.0906, lng: 71.4003 },
    admissionRequirements: {
      entThreshold: 0,
      historyMin: 0,
      profileMin: 0,
      mathLiteracyMin: 0,
      readingLiteracyMin: 0,
      usesEnt: false,
      alternativeTests: {
        nuet: 130,
        sat: 1240,
        act: 27,
        ielts: { overall: 6.0, writing: 6.0, other: 5.5 },
        ibDiploma: 30,
        aLevel: 'ABB'
      }
    },
    totalPrograms: { bachelor: 30, master: 25, phd: 15 },
    teachingLanguages: ['Английский'],
    programs: [
      // School of Engineering and Digital Sciences
      { id: 'chemeng_nu', name: 'Chemical and Materials Engineering', degree: 'Bachelor', price: 0, minScore: 130, grants: 40 },
      { id: 'civileng_nu', name: 'Civil and Environmental Engineering', degree: 'Bachelor', price: 0, minScore: 125, grants: 50 },
      { id: 'eceeng_nu', name: 'Electrical and Computer Engineering', degree: 'Bachelor', price: 0, minScore: 130, grants: 60 },
      { id: 'mecheng_nu', name: 'Mechanical and Aerospace Engineering', degree: 'Bachelor', price: 0, minScore: 128, grants: 45 },
      { id: 'robotics_nu', name: 'Robotics and Mechatronics', degree: 'Bachelor', price: 0, minScore: 130, grants: 40 },
      { id: 'cs_nu', name: 'Computer Science', degree: 'Bachelor', price: 0, minScore: 135, grants: 100 },
      { id: 'datasci_nu', name: 'Data Science', degree: 'Bachelor', price: 0, minScore: 132, grants: 50 },
      // School of Sciences and Humanities
      { id: 'chemistry_nu', name: 'Chemistry', degree: 'Bachelor', price: 0, minScore: 120, grants: 30 },
      { id: 'biology_nu', name: 'Biology', degree: 'Bachelor', price: 0, minScore: 118, grants: 35 },
      { id: 'physics_nu', name: 'Physics', degree: 'Bachelor', price: 0, minScore: 122, grants: 30 },
      { id: 'math_nu', name: 'Mathematics', degree: 'Bachelor', price: 0, minScore: 125, grants: 25 },
      { id: 'economics_nu', name: 'Economics', degree: 'Bachelor', price: 0, minScore: 120, grants: 40 },
      { id: 'polsci_nu', name: 'Political Science and International Relations', degree: 'Bachelor', price: 0, minScore: 118, grants: 35 },
      { id: 'sociology_nu', name: 'Sociology', degree: 'Bachelor', price: 0, minScore: 115, grants: 25 },
      { id: 'history_nu', name: 'History', degree: 'Bachelor', price: 0, minScore: 112, grants: 20 },
      // School of Mining and Geosciences
      { id: 'mining_nu', name: 'Mining Engineering', degree: 'Bachelor', price: 0, minScore: 118, grants: 40 },
      { id: 'petroleum_nu', name: 'Petroleum Engineering', degree: 'Bachelor', price: 0, minScore: 120, grants: 35 },
      { id: 'geosci_nu', name: 'Geological Sciences', degree: 'Bachelor', price: 0, minScore: 115, grants: 30 },
      // Graduate School of Business
      { id: 'bba_nu', name: 'Business Administration', degree: 'Bachelor', price: 0, minScore: 122, grants: 50 },
      // School of Medicine
      { id: 'medicine_nu', name: 'Medicine (MD)', degree: 'Bachelor', price: 0, minScore: 135, grants: 60, duration: 6 },
      // Graduate programs
      { id: 'mba_nu', name: 'Executive MBA', degree: 'Master', price: 0, minScore: 0, grants: 30 },
      { id: 'publicpolicy_nu', name: 'Public Policy', degree: 'Master', price: 0, minScore: 0, grants: 40 },
    ]
  },
  {
    id: 'kaznu',
    name: 'Al-Farabi Kazakh National University',
    shortName: 'KazNU',
    city: 'Almaty',
    rating: 95,
    image: 'https://images.unsplash.com/photo-1562774053-701939374585?q=80&w=800&auto=format&fit=crop', // Green classic campus
    description: 'Ведущий национальный университет Казахстана, старейший вуз страны.',
    type: 'National',
    founded: 1934,
    students: 25000,
    employmentRate: 88,
    dormitory: true,
    militaryDept: true,
    coordinates: { lat: 43.22, lng: 76.9 },
    programs: [
      { id: 'law_kaznu', name: 'International Law', degree: 'Bachelor', price: 1200000, minScore: 110, grants: 50 },
      { id: 'it_kaznu', name: 'Information Systems', degree: 'Bachelor', price: 1100000, minScore: 105, grants: 200 },
    ]
  },
  {
    id: 'kbtu',
    name: 'Kazakh-British Technical University',
    shortName: 'KBTU',
    city: 'Almaty',
    rating: 92,
    image: 'https://images.unsplash.com/photo-1590579491624-f98f36d4c763?q=80&w=800&auto=format&fit=crop', // Classic architecture / columns
    description: 'Один из лидеров технического образования в Центральной Азии.',
    type: 'State',
    founded: 2001,
    students: 4000,
    employmentRate: 98,
    dormitory: true,
    militaryDept: true,
    coordinates: { lat: 43.25, lng: 76.94 },
    programs: [
      { id: 'it_kbtu', name: 'Information Technology', degree: 'Bachelor', price: 1800000, minScore: 115, grants: 120 },
      { id: 'oil_kbtu', name: 'Petroleum Engineering', degree: 'Bachelor', price: 2000000, minScore: 100, grants: 80 },
    ]
  },
  {
    id: 'iitu',
    name: 'International IT University',
    shortName: 'IITU',
    city: 'Almaty',
    rating: 89,
    image: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?q=80&w=800&auto=format&fit=crop', // Modern tech environment
    description: 'Специализированный IT-вуз, готовящий кадры для цифровой экономики.',
    type: 'State',
    founded: 2009,
    students: 5500,
    employmentRate: 94,
    dormitory: true,
    militaryDept: true,
    coordinates: { lat: 43.23, lng: 76.91 },
    programs: [
      { id: 'cs_iitu', name: 'Computer Systems', degree: 'Bachelor', price: 1300000, minScore: 95, grants: 300 },
      { id: 'journ_iitu', name: 'Digital Journalism', degree: 'Bachelor', price: 1000000, minScore: 90, grants: 20 },
    ]
  },
  {
    id: 'sdu',
    name: 'Suleyman Demirel University',
    shortName: 'SDU',
    city: 'Kaskelen',
    rating: 87,
    image: 'https://images.unsplash.com/photo-1504817343863-5092a3238007?q=80&w=800&auto=format&fit=crop', // Students on campus
    description: 'Международный университет с обучением преимущественно на английском языке.',
    type: 'Private',
    founded: 1996,
    students: 7000,
    employmentRate: 85,
    dormitory: true,
    militaryDept: false,
    coordinates: { lat: 43.2, lng: 76.6 },
    programs: [
      { id: 'math_sdu', name: 'Mathematics', degree: 'Bachelor', price: 1500000, minScore: 85, grants: 100 },
      { id: 'ph_sdu', name: 'Philology', degree: 'Bachelor', price: 1200000, minScore: 80, grants: 50 },
    ]
  },
  {
    id: 'enu',
    name: 'L.N. Gumilyov Eurasian National University',
    shortName: 'ENU',
    city: 'Астана',
    rating: 90,
    image: 'https://images.unsplash.com/photo-1562774053-701939374585?q=80&w=800&auto=format&fit=crop',
    description: 'Государственный национальный исследовательский университет в Астане. Входит в топ-400-500 мировых рейтингов (QS, THE). 13 факультетов, 28 научных лабораторий, Институт криптологии, Казахско-Индийский центр с суперкомпьютером.',
    type: 'National',
    founded: 1996,
    students: 17000,
    employmentRate: 89,
    dormitory: true,
    militaryDept: true,
    coordinates: { lat: 51.1605, lng: 71.4704 },
    admissionRequirements: {
      entThreshold: 65,
      historyMin: 5,
      profileMin: 5,
      mathLiteracyMin: 3,
      readingLiteracyMin: 3,
      usesEnt: true
    },
    totalPrograms: { bachelor: 75, master: 50, phd: 30 },
    teachingLanguages: ['Казахский', 'Русский', 'Английский'],
    subjectCombinations: [
      { subjects: ['Математика', 'Физика'], programCount: 15, programs: ['Математика', 'Механика', 'Мат. моделирование', 'Автоматизация', 'Физика', 'Ядерная физика', 'Радиотехника', 'Строительство', 'Электроэнергетика'] },
      { subjects: ['Математика', 'Информатика'], programCount: 5, programs: ['Информатика', 'Вычислительная техника', 'Информационные системы', 'Информационная безопасность', 'ИКТ'] },
      { subjects: ['Математика', 'География'], programCount: 10, programs: ['Геодезия', 'География', 'Экология', 'Экономика', 'Финансы', 'Менеджмент', 'Учет и аудит', 'Маркетинг'] },
      { subjects: ['Биология', 'Химия'], programCount: 6, programs: ['Биология', 'Экология', 'Химия', 'Химия полимеров', 'Неорганическая химия', 'Экоаудит'] },
      { subjects: ['Иностранный язык', 'Всемирная история'], programCount: 4, programs: ['Иностранная филология', 'Переводческое дело', 'Международные отношения', 'Востоковедение'] },
      { subjects: ['История', 'География'], programCount: 4, programs: ['История', 'Археология и этнология', 'Музеология', 'Архивоведение'] },
      { subjects: ['Казахская литература', 'История'], programCount: 3, programs: ['Казахский язык и литература', 'Русский язык и литература', 'Филология'] },
      { subjects: ['Творческий экзамен', ''], programCount: 3, programs: ['Архитектура', 'Дизайн', 'Изобразительное искусство'] }
    ],
    programs: [
      { id: 'math_enu', name: 'Математика', code: '5B010900', degree: 'Bachelor', price: 1000000, minScore: 85, grants: 50, subjects: ['Математика', 'Физика'] },
      { id: 'physics_enu', name: 'Физика', code: '5B060400', degree: 'Bachelor', price: 1000000, minScore: 85, grants: 40, subjects: ['Математика', 'Физика'] },
      { id: 'nuclear_enu', name: 'Ядерная физика', code: '5B060500', degree: 'Bachelor', price: 1100000, minScore: 90, grants: 30, subjects: ['Математика', 'Физика'] },
      { id: 'automation_enu', name: 'Автоматизация и управление', code: '5B070200', degree: 'Bachelor', price: 1100000, minScore: 88, grants: 60, subjects: ['Математика', 'Физика'] },
      { id: 'cs_enu', name: 'Информационные системы', code: '5B070300', degree: 'Bachelor', price: 1100000, minScore: 95, grants: 100, subjects: ['Математика', 'Информатика'] },
      { id: 'it_enu', name: 'Вычислительная техника и ПО', code: '5B070400', degree: 'Bachelor', price: 1100000, minScore: 92, grants: 80, subjects: ['Математика', 'Информатика'] },
      { id: 'infosec_enu', name: 'Системы информационной безопасности', code: '5B100200', degree: 'Bachelor', price: 1150000, minScore: 98, grants: 40, subjects: ['Математика', 'Информатика'] },
      { id: 'construction_enu', name: 'Строительство', degree: 'Bachelor', price: 1050000, minScore: 80, grants: 70, subjects: ['Математика', 'Физика'] },
      { id: 'energy_enu', name: 'Электроэнергетика', degree: 'Bachelor', price: 1050000, minScore: 82, grants: 60, subjects: ['Математика', 'Физика'] },
      { id: 'geodesy_enu', name: 'Геодезия и картография', degree: 'Bachelor', price: 1000000, minScore: 78, grants: 40, subjects: ['Математика', 'География'] },
      { id: 'ecology_enu', name: 'Экология и природопользование', degree: 'Bachelor', price: 1000000, minScore: 75, grants: 50, subjects: ['Математика', 'География'] },
      { id: 'economics_enu', name: 'Экономика', degree: 'Bachelor', price: 1000000, minScore: 85, grants: 100, subjects: ['Математика', 'География'] },
      { id: 'finance_enu', name: 'Финансы', degree: 'Bachelor', price: 1000000, minScore: 88, grants: 80, subjects: ['Математика', 'География'] },
      { id: 'management_enu', name: 'Менеджмент', degree: 'Bachelor', price: 1000000, minScore: 82, grants: 60, subjects: ['Математика', 'География'] },
      { id: 'biology_enu', name: 'Биология', degree: 'Bachelor', price: 950000, minScore: 78, grants: 45, subjects: ['Биология', 'Химия'] },
      { id: 'chemistry_enu', name: 'Химия', degree: 'Bachelor', price: 950000, minScore: 80, grants: 40, subjects: ['Биология', 'Химия'] },
      { id: 'philology_enu', name: 'Иностранная филология', degree: 'Bachelor', price: 1000000, minScore: 85, grants: 60, subjects: ['Иностранный язык', 'Всемирная история'] },
      { id: 'translation_enu', name: 'Переводческое дело', degree: 'Bachelor', price: 1000000, minScore: 88, grants: 50, subjects: ['Иностранный язык', 'Всемирная история'] },
      { id: 'intrel_enu', name: 'Международные отношения', degree: 'Bachelor', price: 1100000, minScore: 95, grants: 40, subjects: ['Иностранный язык', 'Всемирная история'] },
      { id: 'history_enu', name: 'История', degree: 'Bachelor', price: 900000, minScore: 75, grants: 35, subjects: ['История', 'География'] },
      { id: 'archaeology_enu', name: 'Археология и этнология', degree: 'Bachelor', price: 900000, minScore: 72, grants: 25, subjects: ['История', 'География'] },
      { id: 'kazlit_enu', name: 'Казахский язык и литература', degree: 'Bachelor', price: 900000, minScore: 70, grants: 50, subjects: ['Казахская литература', 'История'] },
      { id: 'ruslit_enu', name: 'Русский язык и литература', degree: 'Bachelor', price: 900000, minScore: 70, grants: 40, subjects: ['Русская литература', 'История'] },
      { id: 'arch_enu', name: 'Архитектура', degree: 'Bachelor', price: 1200000, minScore: 85, grants: 30, duration: 5, subjects: ['Творческий экзамен', ''] },
      { id: 'design_enu', name: 'Дизайн', degree: 'Bachelor', price: 1150000, minScore: 80, grants: 25, subjects: ['Творческий экзамен', ''] },
    ]
  },
  {
    id: 'satbayev',
    name: 'Satbayev University',
    shortName: 'SU',
    city: 'Алматы',
    rating: 91,
    image: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?q=80&w=800&auto=format&fit=crop',
    description: 'Казахский национальный исследовательский технический университет имени К.И. Сатпаева. Ведущий технический вуз с 9 образовательными и 6 научно-исследовательскими институтами, FabLab-производственной лабораторией.',
    type: 'National',
    founded: 1934,
    students: 11500,
    employmentRate: 92,
    dormitory: true,
    militaryDept: true,
    coordinates: { lat: 43.2389, lng: 76.9453 },
    admissionRequirements: {
      entThreshold: 65,
      historyMin: 5,
      profileMin: 5,
      mathLiteracyMin: 3,
      readingLiteracyMin: 3,
      usesEnt: true
    },
    totalPrograms: { bachelor: 93, master: 101, phd: 67 },
    teachingLanguages: ['Казахский', 'Русский', 'Английский'],
    grantsPerYear: 2000,
    subjectCombinations: [
      { subjects: ['Математика', 'Физика'], programCount: 48, programs: ['Горное дело', 'Нефтегазовое дело', 'Геология', 'Металлургия', 'Машиностроение', 'Робототехника', 'Электроэнергетика', 'Строительство', 'Архитектура', 'Космическая техника'] },
      { subjects: ['Математика', 'Информатика'], programCount: 6, programs: ['Информационные системы', 'Computer Science', 'Информационная безопасность', 'Телекоммуникации', 'Биомедицинская инженерия'] },
      { subjects: ['Математика', 'География'], programCount: 11, programs: ['Геопространственная инженерия', 'Землеустройство', 'Экономика', 'Финансовая аналитика', 'Бизнес-инжиниринг', 'Менеджмент', 'Логистика'] },
      { subjects: ['Биология', 'География'], programCount: 1, programs: ['Экология'] },
      { subjects: ['Биология', 'Химия'], programCount: 2, programs: ['Биотехнология', 'Технология фармпроизводства'] },
      { subjects: ['Химия', 'Физика'], programCount: 3, programs: ['Химическая технология', 'Нефтехимия', 'Полимеры'] },
      { subjects: ['Творческий экзамен', ''], programCount: 2, programs: ['Архитектура', 'Дизайн'] }
    ],
    programs: [
      { id: 'mining_su', name: 'Горное дело', degree: 'Bachelor', price: 1300000, minScore: 75, grants: 150, subjects: ['Математика', 'Физика'] },
      { id: 'oil_su', name: 'Нефтегазовое дело', degree: 'Bachelor', price: 1400000, minScore: 80, grants: 200, subjects: ['Математика', 'Физика'] },
      { id: 'drilling_su', name: 'Бурение нефтяных и газовых скважин', degree: 'Bachelor', price: 1350000, minScore: 78, grants: 100, subjects: ['Математика', 'Физика'] },
      { id: 'geology_su', name: 'Геология и разведка', degree: 'Bachelor', price: 1250000, minScore: 72, grants: 120, subjects: ['Математика', 'Физика'] },
      { id: 'mineral_su', name: 'Обогащение полезных ископаемых', degree: 'Bachelor', price: 1200000, minScore: 70, grants: 80, subjects: ['Математика', 'Физика'] },
      { id: 'metallurgy_su', name: 'Металлургия', degree: 'Bachelor', price: 1250000, minScore: 72, grants: 100, subjects: ['Математика', 'Физика'] },
      { id: 'materials_su', name: 'Инженерная физика и материаловедение', degree: 'Bachelor', price: 1200000, minScore: 75, grants: 60, subjects: ['Математика', 'Физика'] },
      { id: 'mechanical_su', name: 'Машиностроение', degree: 'Bachelor', price: 1200000, minScore: 73, grants: 90, subjects: ['Математика', 'Физика'] },
      { id: 'robotics_su', name: 'Робототехника и мехатроника', degree: 'Bachelor', price: 1350000, minScore: 82, grants: 70, subjects: ['Математика', 'Физика'] },
      { id: 'automation_su', name: 'Автоматизация и роботизация', degree: 'Bachelor', price: 1300000, minScore: 80, grants: 80, subjects: ['Математика', 'Физика'] },
      { id: 'electronics_su', name: 'Электроника и электротехника', degree: 'Bachelor', price: 1200000, minScore: 78, grants: 100, subjects: ['Математика', 'Физика'] },
      { id: 'energy_su', name: 'Электроэнергетика', degree: 'Bachelor', price: 1150000, minScore: 76, grants: 120, subjects: ['Математика', 'Физика'] },
      { id: 'nuclear_su', name: 'Ядерная энергетика', degree: 'Bachelor', price: 1400000, minScore: 85, grants: 40, subjects: ['Математика', 'Физика'] },
      { id: 'thermal_su', name: 'Теплоэнергетика', degree: 'Bachelor', price: 1150000, minScore: 74, grants: 80, subjects: ['Математика', 'Физика'] },
      { id: 'space_su', name: 'Космическая техника и технологии', degree: 'Bachelor', price: 1500000, minScore: 88, grants: 30, subjects: ['Математика', 'Физика'] },
      { id: 'transport_su', name: 'Транспортная инженерия', degree: 'Bachelor', price: 1200000, minScore: 72, grants: 90, subjects: ['Математика', 'Физика'] },
      { id: 'construction_su', name: 'Строительство', degree: 'Bachelor', price: 1300000, minScore: 75, grants: 150, subjects: ['Математика', 'Физика'] },
      { id: 'arch_su', name: 'Архитектура', degree: 'Bachelor', price: 1400000, minScore: 82, grants: 60, duration: 5, subjects: ['Творческий экзамен', ''] },
      { id: 'utilities_su', name: 'Инженерные системы и сети', degree: 'Bachelor', price: 1250000, minScore: 73, grants: 80, subjects: ['Математика', 'Физика'] },
      { id: 'cs_su', name: 'Computer Science', degree: 'Bachelor', price: 1350000, minScore: 88, grants: 150, subjects: ['Математика', 'Информатика'] },
      { id: 'is_su', name: 'Информационные системы', degree: 'Bachelor', price: 1300000, minScore: 85, grants: 180, subjects: ['Математика', 'Информатика'] },
      { id: 'infosec_su', name: 'Информационная безопасность', degree: 'Bachelor', price: 1400000, minScore: 90, grants: 80, subjects: ['Математика', 'Информатика'] },
      { id: 'telecom_su', name: 'Телекоммуникации', degree: 'Bachelor', price: 1250000, minScore: 82, grants: 100, subjects: ['Математика', 'Информатика'] },
      { id: 'biomedeng_su', name: 'Биомедицинская инженерия', degree: 'Bachelor', price: 1400000, minScore: 85, grants: 40, subjects: ['Математика', 'Информатика'] },
      { id: 'geodigital_su', name: 'Геопространственная цифровая инженерия', degree: 'Bachelor', price: 1200000, minScore: 75, grants: 50, subjects: ['Математика', 'География'] },
      { id: 'land_su', name: 'Землеустройство и кадастр', degree: 'Bachelor', price: 1150000, minScore: 72, grants: 60, subjects: ['Математика', 'География'] },
      { id: 'ecology_su', name: 'Инженерная экология', degree: 'Bachelor', price: 1100000, minScore: 70, grants: 70, subjects: ['Биология', 'География'] },
      { id: 'finanalytics_su', name: 'Финансовая аналитика', degree: 'Bachelor', price: 1200000, minScore: 78, grants: 80, subjects: ['Математика', 'География'] },
      { id: 'business_su', name: 'Бизнес-инжиниринг', degree: 'Bachelor', price: 1250000, minScore: 80, grants: 70, subjects: ['Математика', 'География'] },
      { id: 'biotech_su', name: 'Биотехнология', degree: 'Bachelor', price: 1300000, minScore: 78, grants: 50, subjects: ['Биология', 'Химия'] },
      { id: 'pharmatech_su', name: 'Технология фармпроизводства', degree: 'Bachelor', price: 1350000, minScore: 80, grants: 40, subjects: ['Биология', 'Химия'] },
      { id: 'chemtech_su', name: 'Химическая технология', degree: 'Bachelor', price: 1200000, minScore: 75, grants: 60, subjects: ['Химия', 'Физика'] },
      { id: 'petrochemtech_su', name: 'Нефтехимия', degree: 'Bachelor', price: 1300000, minScore: 78, grants: 70, subjects: ['Химия', 'Физика'] },
    ]
  },
  {
    id: 'ayu',
    name: 'Khoja Akhmet Yassawi International Kazakh-Turkish University',
    shortName: 'AYU',
    city: 'Туркестан',
    rating: 85,
    image: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?q=80&w=800&auto=format&fit=crop',
    description: 'Международный казахско-турецкий университет имени Х.А. Ясави. Создан на основе межправительственного соглашения Казахстана и Турции. Студенты из 30+ тюркоязычных стран.',
    type: 'International',
    founded: 1991,
    students: 8500,
    employmentRate: 82,
    dormitory: true,
    militaryDept: true,
    coordinates: { lat: 43.2975, lng: 68.2514 },
    admissionRequirements: {
      entThreshold: 65,
      historyMin: 5,
      profileMin: 5,
      mathLiteracyMin: 3,
      readingLiteracyMin: 3,
      usesEnt: true
    },
    totalPrograms: { bachelor: 91, master: 44, phd: 14, residency: 33 },
    teachingLanguages: ['Казахский', 'Турецкий', 'Русский', 'Английский'],
    subjectCombinations: [
      { subjects: ['Математика', 'Физика'], programCount: 7, programs: ['Математика', 'Физика', 'Автоматизация', 'ИС', 'Вычислительная техника', 'Электроэнергетика', 'БЖД'] },
      { subjects: ['Математика', 'Информатика'], programCount: 3, programs: ['Информатика', 'Вычислительная техника и ПО'] },
      { subjects: ['Математика', 'География'], programCount: 5, programs: ['Экономика', 'Менеджмент', 'Учет и аудит', 'Финансы', 'ГМУ'] },
      { subjects: ['Биология', 'Химия'], programCount: 7, programs: ['Медицина', 'Стоматология', 'Биология', 'Химия', 'Экология', 'Фармация', 'Ветеринария'] },
      { subjects: ['Иностранный язык', 'Всемирная история'], programCount: 3, programs: ['Иностранная филология', 'Переводческое дело', 'Два иностранных языка'] },
      { subjects: ['История', 'География'], programCount: 3, programs: ['История', 'География', 'Туризм'] },
      { subjects: ['Казахская литература', 'История'], programCount: 6, programs: ['Казахский язык и литература', 'Русский язык и литература', 'Филология', 'Теология', 'Религиоведение', 'Тюркология'] },
      { subjects: ['Творческий экзамен', ''], programCount: 3, programs: ['Дизайн', 'Музыкальное образование', 'Изобразительное искусство'] }
    ],
    programs: [
      { id: 'math_ayu', name: 'Математика', code: '5B010900', degree: 'Bachelor', price: 550000, minScore: 70, grants: 40, subjects: ['Математика', 'Физика'] },
      { id: 'physics_ayu', name: 'Физика', code: '5B011000', degree: 'Bachelor', price: 550000, minScore: 70, grants: 35, subjects: ['Математика', 'Физика'] },
      { id: 'automation_ayu', name: 'Автоматизация и управление', code: '5B070200', degree: 'Bachelor', price: 600000, minScore: 72, grants: 50, subjects: ['Математика', 'Физика'] },
      { id: 'is_ayu', name: 'Информационные системы', code: '5B070300', degree: 'Bachelor', price: 600000, minScore: 73, grants: 60, subjects: ['Математика', 'Физика'] },
      { id: 'it_ayu', name: 'Вычислительная техника и ПО', code: '5B070400', degree: 'Bachelor', price: 600000, minScore: 75, grants: 55, subjects: ['Математика', 'Информатика'] },
      { id: 'energy_ayu', name: 'Электроэнергетика', code: '5B071800', degree: 'Bachelor', price: 580000, minScore: 68, grants: 45, subjects: ['Математика', 'Физика'] },
      { id: 'informatics_ayu', name: 'Информатика', code: '5B011100', degree: 'Bachelor', price: 550000, minScore: 72, grants: 50, subjects: ['Математика', 'Информатика'] },
      { id: 'economics_ayu', name: 'Экономика', code: '5B050600', degree: 'Bachelor', price: 550000, minScore: 75, grants: 60, subjects: ['Математика', 'География'] },
      { id: 'management_ayu', name: 'Менеджмент', code: '5B050700', degree: 'Bachelor', price: 550000, minScore: 72, grants: 50, subjects: ['Математика', 'География'] },
      { id: 'accounting_ayu', name: 'Учет и аудит', code: '5B050800', degree: 'Bachelor', price: 550000, minScore: 70, grants: 45, subjects: ['Математика', 'География'] },
      { id: 'finance_ayu', name: 'Финансы', code: '5B050900', degree: 'Bachelor', price: 550000, minScore: 73, grants: 55, subjects: ['Математика', 'География'] },
      { id: 'gmu_ayu', name: 'Государственное и местное управление', code: '5B051000', degree: 'Bachelor', price: 550000, minScore: 75, grants: 40, subjects: ['Математика', 'География'] },
      { id: 'medicine_ayu', name: 'Общая медицина', code: 'BM086', degree: 'Bachelor', price: 850000, minScore: 93, grants: 80, duration: 6, subjects: ['Биология', 'Химия'] },
      { id: 'stomatology_ayu', name: 'Стоматология', code: 'BM087', degree: 'Bachelor', price: 900000, minScore: 95, grants: 50, duration: 5, subjects: ['Биология', 'Химия'] },
      { id: 'biology_ayu', name: 'Биология', code: '5B011300', degree: 'Bachelor', price: 500000, minScore: 68, grants: 40, subjects: ['Биология', 'Химия'] },
      { id: 'chemistry_ayu', name: 'Химия', code: '5B011200', degree: 'Bachelor', price: 500000, minScore: 68, grants: 35, subjects: ['Биология', 'Химия'] },
      { id: 'ecology_ayu', name: 'Экология', code: '5B060800', degree: 'Bachelor', price: 500000, minScore: 65, grants: 45, subjects: ['Биология', 'Химия'] },
      { id: 'foreignphil_ayu', name: 'Иностранная филология', code: '5B021000', degree: 'Bachelor', price: 550000, minScore: 72, grants: 60, subjects: ['Иностранный язык', 'Всемирная история'] },
      { id: 'translation_ayu', name: 'Переводческое дело', code: '5B020700', degree: 'Bachelor', price: 550000, minScore: 75, grants: 50, subjects: ['Иностранный язык', 'Всемирная история'] },
      { id: 'twolang_ayu', name: 'Два иностранных языка', code: '5B011900', degree: 'Bachelor', price: 550000, minScore: 70, grants: 45, subjects: ['Иностранный язык', 'Всемирная история'] },
      { id: 'history_ayu', name: 'История', code: '5B011400', degree: 'Bachelor', price: 500000, minScore: 68, grants: 35, subjects: ['История', 'География'] },
      { id: 'geography_ayu', name: 'География', code: '5B011600', degree: 'Bachelor', price: 500000, minScore: 65, grants: 30, subjects: ['История', 'География'] },
      { id: 'tourism_ayu', name: 'Туризм', code: '5B090200', degree: 'Bachelor', price: 550000, minScore: 70, grants: 40, subjects: ['История', 'География'] },
      { id: 'kazlit_ayu', name: 'Казахский язык и литература', code: '5B011700', degree: 'Bachelor', price: 500000, minScore: 65, grants: 50, subjects: ['Казахская литература', 'История'] },
      { id: 'ruslit_ayu', name: 'Русский язык и литература', code: '5B011800', degree: 'Bachelor', price: 500000, minScore: 65, grants: 40, subjects: ['Русская литература', 'История'] },
      { id: 'philology_ayu', name: 'Филология', code: '5B020500', degree: 'Bachelor', price: 500000, minScore: 68, grants: 35, subjects: ['Казахская литература', 'История'] },
      { id: 'theology_ayu', name: 'Теология', code: '5B021100', degree: 'Bachelor', price: 500000, minScore: 65, grants: 30, subjects: ['Казахская литература', 'История'] },
      { id: 'religion_ayu', name: 'Религиоведение', code: '5B020600', degree: 'Bachelor', price: 500000, minScore: 65, grants: 25, subjects: ['Казахская литература', 'История'] },
      { id: 'turkology_ayu', name: 'Тюркология', code: '5B021200', degree: 'Bachelor', price: 550000, minScore: 70, grants: 35, subjects: ['Казахская литература', 'История'] },
      { id: 'design_ayu', name: 'Дизайн', code: '5B042100', degree: 'Bachelor', price: 550000, minScore: 65, grants: 30, subjects: ['Творческий экзамен', ''] },
      { id: 'music_ayu', name: 'Музыкальное образование', code: '5B010600', degree: 'Bachelor', price: 500000, minScore: 60, grants: 25, subjects: ['Творческий экзамен', ''] },
      { id: 'art_ayu', name: 'Изобразительное искусство', code: '5B010700', degree: 'Bachelor', price: 500000, minScore: 60, grants: 25, subjects: ['Творческий экзамен', ''] },
    ]
  },
  {
    id: 'kaznmu',
    name: 'Kazakh National Medical University named after S.D. Asfendiyarov',
    shortName: 'KazNMU',
    city: 'Алматы',
    rating: 93,
    image: 'https://images.unsplash.com/photo-1551076805-e1869033e561?q=80&w=800&auto=format&fit=crop',
    description: 'Казахский национальный медицинский университет имени С.Д. Асфендиярова. Первый медицинский вуз Казахстана (основан в 1930-1931). Университетская клиника, симуляционные и анатомические лаборатории. ~11 000 студентов, ~1 500 преподавателей.',
    type: 'National',
    founded: 1931,
    students: 11000,
    employmentRate: 95,
    dormitory: true,
    militaryDept: true,
    coordinates: { lat: 43.2567, lng: 76.9286 },
    admissionRequirements: {
      entThreshold: 70,
      historyMin: 5,
      profileMin: 5,
      mathLiteracyMin: 3,
      readingLiteracyMin: 3,
      usesEnt: true
    },
    totalPrograms: { bachelor: 9, master: 20, phd: 10, residency: 50 },
    teachingLanguages: ['Казахский', 'Русский', 'Английский'],
    subjectCombinations: [
      { subjects: ['Биология', 'Химия'], programCount: 9, programs: ['Стоматология', 'Общая медицина', 'Фармация', 'Педиатрия', 'Общественное здоровье', 'Медико-профилактическое дело', 'Сестринское дело', 'Технология фармпроизводства', 'Клиническая психология'] }
    ],
    programs: [
      { id: 'stomatology_kaznmu', name: 'Стоматология', code: 'BM087', degree: 'Bachelor', price: 2100000, minScore: 136, grants: 100, duration: 5, subjects: ['Биология', 'Химия'] },
      { id: 'public_health_kaznmu', name: 'Общественное здоровье', code: 'B089', degree: 'Bachelor', price: 1600000, minScore: 125, grants: 80, subjects: ['Биология', 'Химия'], ruralQuotaScore: 96 },
      { id: 'medicine_kaznmu', name: 'Общая медицина', code: 'BM086', degree: 'Bachelor', price: 1900000, minScore: 124, grants: 300, duration: 6, subjects: ['Биология', 'Химия'], ruralQuotaScore: 115 },
      { id: 'pharmacy_kaznmu', name: 'Фармация', code: 'B085', degree: 'Bachelor', price: 1500000, minScore: 124, grants: 150, subjects: ['Биология', 'Химия'], ruralQuotaScore: 107 },
      { id: 'pediatrics_kaznmu', name: 'Педиатрия', code: 'BM088', degree: 'Bachelor', price: 1800000, minScore: 111, grants: 200, duration: 6, subjects: ['Биология', 'Химия'], ruralQuotaScore: 100 },
      { id: 'preventive_kaznmu', name: 'Медико-профилактическое дело', code: 'BM089', degree: 'Bachelor', price: 1600000, minScore: 108, grants: 120, duration: 5, subjects: ['Биология', 'Химия'], ruralQuotaScore: 95 },
      { id: 'nursing_kaznmu', name: 'Сестринское дело', code: 'B084', degree: 'Bachelor', price: 1200000, minScore: 95, grants: 60, subjects: ['Биология', 'Химия'], ruralQuotaScore: 92 },
      { id: 'pharmatech_kaznmu', name: 'Технология фармацевтического производства', code: 'B072', degree: 'Bachelor', price: 1111400, minScore: 75, grants: 40, subjects: ['Биология', 'Химия'] },
      { id: 'clinpsych_kaznmu', name: 'Клиническая психология', degree: 'Bachelor', price: 1400000, minScore: 90, grants: 30, subjects: ['Биология', 'Химия'] },
    ]
  }
];

export const COMPARISON_METRICS: ComparisonMetric[] = [
  { label: 'Рейтинг', key: 'rating', format: (v: number) => `${v}/100`, higherIsBetter: true },
  { label: 'Трудоустройство', key: 'employmentRate', format: (v: number) => `${v}%`, higherIsBetter: true },
  { label: 'Студентов', key: 'students', format: (v: number) => v.toLocaleString(), higherIsBetter: true },
  { label: 'Год основания', key: 'founded', format: (v: number) => v.toString(), disableRelative: true },
  { label: 'Общежитие', key: 'dormitory', format: (v: boolean) => v ? 'Есть' : 'Нет', disableRelative: true },
  { label: 'Военная кафедра', key: 'militaryDept', format: (v: boolean) => v ? 'Есть' : 'Нет', disableRelative: true },
];
